#!/usr/bin/env python3
"""Read-only source/fixture/tool recipe verification; never builds or runs RTL."""
from pathlib import Path
import hashlib,json,re,sys
ROOT=Path(__file__).resolve().parent; C=ROOT/'candidate'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
rows={}
for line in (C/'source_manifest.sha256').read_text().splitlines():
 h,n=line.split('  ',1);assert n not in rows and re.fullmatch(r'[0-9a-f]{64}',h);rows[n]=h
assert len(rows)==128
assert set(rows)=={p.relative_to(C).as_posix() for p in C.rglob('*') if p.is_file() and p.name!='source_manifest.sha256' and 'run' not in p.relative_to(C).parts and p.name not in {'supervisor.json','stdout.log','measurement.json','profile_check.log','postrun_source_manifest.sha256'}}
for rel,h in rows.items():assert sha(C/rel)==h,rel
assert not (C/'run').exists() and not (C/'obj').exists()
assert sha(C/'tree/rtl/ap68040/rtl/ap040_cache.v')=='9e8c0582db1b0bb88428e56fec63e99029b61faffac62c6f3dda9326b5191481'
assert sha(C/'tree/rtl/ap68040/rtl/ap040_fpu.v')=='6c157b3bc045e74a90416f4764f35cf65024e77577019a100b8aa9b5bdd9ce9b'
assert sha(C/'ram.bin')=='9e58e9b226e03acbee4e1ae690a8b67500328dfb5933df55e1b832c926c653e9'
assert sha(C/'assets/quadra800.rom')=='7d9cb8c3bae0e26171adf9f24bedf10bf6371ae3c9bdbcdfd3b94e5350099fb6'
assert sha(C/'tb_platform_whet.sv')=='08b5135917174ea4269c156e1f618988176e2e22b558798a1eeb1d61baeae5cb'
assert sha(C/'next_monitor.svh')==sha(ROOT.parent/'native_whet_next_measurement_20260928/profile/next_monitor.svh')
assert sha(C/'run_platform_whet.py')==sha(ROOT.parent/'native_whet_next_measurement_20260928/profile/run_platform_whet.py')
assert sha(C/'check_result.py')==sha(ROOT.parent/'native_whet_next_measurement_20260928/profile/check_result.py')
# Independently check every source consumed by the qualified baseline runner.
refmeta=json.loads((ROOT/'baseline_reference.json').read_text())
archive=ROOT.parent.parent/refmeta['archive']/'run'
base_run_identity=json.loads((archive/'identity.json').read_text())
for source,digest in base_run_identity['sources'].items():
 rel=source.split('/profile/',1)[1]
 if rel.startswith('tree/'):
  q=C/rel
 elif rel.startswith('assets/'):
  q=C/rel
 elif rel=='tb_platform_whet.sv':
  q=C/rel
 elif rel=='run/sdram_model_flat.sv':
  raw=(C/'assets/tb_sdram.sv').read_text(); model=raw[raw.index('module sdram_model'):]
  for old,new in [('bit [15:0] mem [int];','bit [15:0] mem [0:33554431];'),("mem.exists(k) ? mem[k] : 16'hFFFF",'mem[k]'),("if (!mem.exists(k)) mem[k] = 16'hFFFF;",'')]:
   assert old in model; model=model.replace(old,new)
  flat='// GENERATED by run_platform_whet.py from verilator/tb_sdram.sv (storage flattened)\n`timescale 1ps/1ps\n'+model
  assert hashlib.sha256(flat.encode()).hexdigest()==digest,'baseline generated SDRAM model identity'
  continue
 else: raise AssertionError(f'unmapped original compile source {rel}')
 assert q.is_file(),rel
 if rel=='tree/rtl/ap68040/rtl/ap040_cache.v':
  assert digest=='7cba7f73f6f7f16fa7a45d439af6a786bd55c3ef2a3f8c876b400e10d4fb7747'
 else: assert sha(q)==digest,rel
assert len(base_run_identity["sources"])==32
# The candidate source tree must differ from its frozen baseline only at cache RTL.
old=ROOT.parent/'native_whet_next_measurement_20260928/profile/tree'; diffs=[]
for p in old.rglob('*'):
 if p.is_file():
  q=C/'tree'/p.relative_to(old); assert q.is_file()
  if sha(p)!=sha(q):diffs.append((p.relative_to(old).as_posix(),sha(p),sha(q)))
assert len(diffs)==1 and diffs[0][0]=='rtl/ap68040/rtl/ap040_cache.v',diffs
assert len([p for p in old.rglob('*') if p.is_file()])==113
# The benchmark reference is pinned to the prior qualified joint-profile run.
ref=json.loads((ROOT/'baseline_reference.json').read_text()); archive=ROOT.parent.parent/ref['archive']/'run'
assert sha(archive/'identity.json')==ref['run_identity_sha256'] and sha(archive/'run.log')==ref['run_log_sha256']
assert ref['loop_cycles']==8724166 and ref['romlat']==6
for n,h in ref['captures'].items():assert sha(archive/n)==h,n
identity=json.loads((archive/'identity.json').read_text())
assert identity['image_sha256']==ref['image_sha256'] and identity['rom_sha256']==ref['rom_sha256'] and identity['romlat']==6
assert identity['flags']==['-DAP040_EXPERIMENTAL_XSTORE','-DAP040_EXPERIMENTAL_LEA','-DAP040_EXPERIMENTAL_PIPELINE','-DAP040_EXPERIMENTAL_PIPELINE_LOADS','-DAP040_EXPERIMENTAL_PIPELINE_STORES','-DAP040_EXPERIMENTAL_PIPELINE_PEA','-DAP040_EXPERIMENTAL_PIPELINE_P6','-DAP040_PIPELINE_MEMORY_ENTRY','-DAP040_PIPELINE_COMPARE','-DAP040_PIPELINE_EARLY_DRAIN','-DCACHE_CD_OFF=1','-DCACHE_SMALL=1','-DSIMULATION=1']
print(json.dumps({'status':'PREPARATION_PASS_ONLY_NO_BUILD_OR_RUN','candidate_manifest_count':len(rows),'candidate_manifest_sha256':sha(C/'source_manifest.sha256'),'RTL_tree_files':113,'sole_RTL_delta':diffs[0][0],'candidate_cache_sha256':diffs[0][2],'candidate_fpu_sha256':sha(C/'tree/rtl/ap68040/rtl/ap040_fpu.v'),'baseline_profile_log_sha256':ref['run_log_sha256'],'baseline_loop_cycles':ref['loop_cycles'],'ROMlat':6,'RAM_sha256':sha(C/'ram.bin'),'ROM_sha256':sha(C/'assets/quadra800.rom')},indent=2))
