; generated by gen_t_fpu_addr.py -- P256 d16 / brief-indexed FPU operand check
FAILREG equ $F100
OUTC    equ $6000
    org 0
    dc.l $7000,start
    rept 254
    dc.l failed
    endr
    org $400
start:
    move.l #$80008000,d0
    movec d0,cacr
    fmove.l #0,fpcr
    moveq #0,d7
; ---- d16(An) source
	lea	$5000,a0
	fmove.s	8(a0),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40002000,(OUTC).l
	beq	ok1
	move.w	#1,d7
	jmp	failed
ok1:
	lea	$5040,a0
	fmove.s	-12(a0),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$4000d000,(OUTC).l
	beq	ok2
	move.w	#2,d7
	jmp	failed
ok2:
	lea	($ffffe010).l,a1
	fmove.s	$7000(a1),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40004000,(OUTC).l
	beq	ok3
	move.w	#3,d7
	jmp	failed
ok3:
	lea	($cff0).l,a1
	fmove.s	-$7fe0(a1),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40004000,(OUTC).l
	beq	ok4
	move.w	#4,d7
	jmp	failed
ok4:
; ---- base written by the previous instruction
	lea	$5020,a3
	fmove.s	4(a3),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40009000,(OUTC).l
	beq	ok5
	move.w	#5,d7
	jmp	failed
ok5:
	move.l	#$5000,a3
	addq.l	#8,a3
	fmove.s	4(a3),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40003000,(OUTC).l
	beq	ok6
	move.w	#6,d7
	jmp	failed
ok6:
; ---- brief indexed source, data index
	lea	$5000,a0
	moveq	#8,d1
	fmove.s	4(a0,d1.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40003000,(OUTC).l
	beq	ok7
	move.w	#7,d7
	jmp	failed
ok7:
	move.l	#$ffff0005,d1
	fmove.s	-8(a0,d1.w*4),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40003000,(OUTC).l
	beq	ok8
	move.w	#8,d7
	jmp	failed
ok8:
	move.l	#$0001fffe,d1
	lea	$5040,a2
	fmove.s	8(a2,d1.w*2),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40011000,(OUTC).l
	beq	ok9
	move.w	#9,d7
	jmp	failed
ok9:
	moveq	#3,d2
	fmove.s	0(a0,d2.l*8),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40006000,(OUTC).l
	beq	ok10
	move.w	#10,d7
	jmp	failed
ok10:
	moveq	#1,d2
	fmove.s	$7f(a0,d2.l*1),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40020000,(OUTC).l
	beq	ok11
	move.w	#11,d7
	jmp	failed
ok11:
	moveq	#$20,d2
	fmove.s	-$80(a0,d2.l*4),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40000000,(OUTC).l
	beq	ok12
	move.w	#12,d7
	jmp	failed
ok12:
; ---- index written by the previous instruction
	moveq	#12,d2
	fmove.s	0(a0,d2.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40003000,(OUTC).l
	beq	ok13
	move.w	#13,d7
	jmp	failed
ok13:
	moveq	#12,d2
	addq.l	#4,d2
	fmove.s	0(a0,d2.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40004000,(OUTC).l
	beq	ok14
	move.w	#14,d7
	jmp	failed
ok14:
	move.l	#20,d3
	move.l	 d3,d4
	fmove.s	0(a0,d4.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40005000,(OUTC).l
	beq	ok15
	move.w	#15,d7
	jmp	failed
ok15:
	moveq	#6,d4
	lsl.l	#2,d4
	fmove.s	0(a0,d4.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40006000,(OUTC).l
	beq	ok16
	move.w	#16,d7
	jmp	failed
ok16:
; ---- address-register index
	move.l	#$28,a1
	fmove.s	0(a0,a1.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$4000a000,(OUTC).l
	beq	ok17
	move.w	#17,d7
	jmp	failed
ok17:
	lea	$2c,a1
	fmove.s	0(a0,a1.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$4000b000,(OUTC).l
	beq	ok18
	move.w	#18,d7
	jmp	failed
ok18:
	lea	4(a1),a1
	fmove.s	0(a0,a1.w),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$4000c000,(OUTC).l
	beq	ok19
	move.w	#19,d7
	jmp	failed
ok19:
	move.l	#$fffffffc,a1
	lea	$5038,a2
	fmove.s	0(a2,a1.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$4000d000,(OUTC).l
	beq	ok20
	move.w	#20,d7
	jmp	failed
ok20:
; ---- index/base = same register
	move.l	#$2808,a4
	fmove.s	-16(a4,a4.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40000000,(OUTC).l
	beq	ok21
	move.w	#21,d7
	jmp	failed
ok21:
; ---- index and base updated by a preceding FP (An)+ / -(An)
	lea	$5040,a5
	fmove.s	(a5)+,fp3
	fmove.s	0(a5),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40011000,(OUTC).l
	beq	ok22
	move.w	#22,d7
	jmp	failed
ok22:
	lea	$5040,a5
	sub.l	a6,a6
	fmove.s	(a5)+,fp3
	fmove.s	4(a6,a5.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40012000,(OUTC).l
	beq	ok23
	move.w	#23,d7
	jmp	failed
ok23:
	lea	$5050,a5
	fmove.s	-(a5),fp3
	fmove.s	-4(a5),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40012000,(OUTC).l
	beq	ok24
	move.w	#24,d7
	jmp	failed
ok24:
	lea	$5050,a5
	fmove.s	-(a5),fp3
	fmove.s	0(a6,a5.w),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40013000,(OUTC).l
	beq	ok25
	move.w	#25,d7
	jmp	failed
ok25:
; ---- A7 base / index
	move.l	a7,d6
	lea	$5060,a7
	fmove.s	4(a7),fp0
	move.l	d6,a7
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40019000,(OUTC).l
	beq	ok26
	move.w	#26,d7
	jmp	failed
ok26:
	move.l	a7,d6
	move.l	#$68,a7
	fmove.s	0(a0,a7.l),fp0
	move.l	d6,a7
	fmove.s	fp0,(OUTC).l
	cmp.l	#$4001a000,(OUTC).l
	beq	ok27
	move.w	#27,d7
	jmp	failed
ok27:
; ---- PC-relative sources
	bra.s	pcskip
	cnop	0,4
pctab:
	dc.l	$3f800000,$3fa00000,$3fc00000,$3fe00000
pcskip:
	fmove.s	pctab+8(pc),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$3fc00000,(OUTC).l
	beq	ok28
	move.w	#28,d7
	jmp	failed
ok28:
	moveq	#4,d1
	fmove.s	pctab(pc,d1.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$3fa00000,(OUTC).l
	beq	ok29
	move.w	#29,d7
	jmp	failed
ok29:
	move.l	#$ffff0003,d1
	fmove.s	pctab(pc,d1.w*4),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$3fe00000,(OUTC).l
	beq	ok30
	move.w	#30,d7
	jmp	failed
ok30:
	moveq	#12,d1
	fmove.s	pctab-4(pc,d1.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$3fc00000,(OUTC).l
	beq	ok31
	move.w	#31,d7
	jmp	failed
ok31:
; ---- full-format extension (fallback path)
	moveq	#8,d1
	fmove.s	(4.l,a0,d1.l),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40003000,(OUTC).l
	beq	ok32
	move.w	#32,d7
	jmp	failed
ok32:
	move.l	#$5070,(ptr).l
	fmove.s	([ptr.l],4),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$4001d000,(OUTC).l
	beq	ok33
	move.w	#33,d7
	jmp	failed
ok33:
	fmove.s	(-4.w,a0,d1.l*2),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40003000,(OUTC).l
	beq	ok34
	move.w	#34,d7
	jmp	failed
ok34:
; ---- double sources
	lea	$5400,a0
	fmove.d	16(a0),fp1
	fmove.d	fp1,(OUTC).l
	cmp.l	#$40002000,(OUTC).l
	bne	bad35
	cmp.l	#$1234567a,(OUTC+4).l
	beq	ok35
bad35:
	move.w	#35,d7
	jmp	failed
ok35:
	moveq	#3,d1
	fmove.d	8(a0,d1.l*8),fp1
	fmove.d	fp1,(OUTC).l
	cmp.l	#$40004000,(OUTC).l
	bne	bad36
	cmp.l	#$1234567c,(OUTC+4).l
	beq	ok36
bad36:
	move.w	#36,d7
	jmp	failed
ok36:
	moveq	#40,d1
	fmove.d	0(a0,d1.w),fp1
	fmove.d	fp1,(OUTC).l
	cmp.l	#$40005000,(OUTC).l
	bne	bad37
	cmp.l	#$1234567d,(OUTC+4).l
	beq	ok37
bad37:
	move.w	#37,d7
	jmp	failed
ok37:
	fmove.d	pcd(pc),fp1
	fmove.d	fp1,(OUTC).l
	cmp.l	#$40091eb8,(OUTC).l
	bne	bad38
	cmp.l	#$51eb851f,(OUTC+4).l
	beq	ok38
bad38:
	move.w	#38,d7
	jmp	failed
ok38:
; ---- arithmetic with displacement / indexed sources
	lea	$5000,a0
	fmove.s	#2.0,fp0
	fmul.s	8(a0),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40802000,(OUTC).l
	beq	ok39
	move.w	#39,d7
	jmp	failed
ok39:
	fmove.s	#1.0,fp0
	moveq	#4,d1
	fmul.s	0(a0,d1.l*4),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40004000,(OUTC).l
	beq	ok40
	move.w	#40,d7
	jmp	failed
ok40:
	fmove.s	#0.0,fp0
	fadd.s	-4(a0,d1.l*8),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$40007000,(OUTC).l
	beq	ok41
	move.w	#41,d7
	jmp	failed
ok41:
	fmove.s	#2.0,fp0
	lea	pctab,a2
	fdiv.s	8(a2),fp0
	fmove.s	fp0,(OUTC).l
	cmp.l	#$3faaaaab,(OUTC).l
	beq	ok42
	move.w	#42,d7
	jmp	failed
ok42:
	lea	$5400,a0
	fmove.s	#1.0,fp1
	fmul.d	16(a0),fp1
	fmove.d	fp1,(OUTC).l
	cmp.l	#$40002000,(OUTC).l
	bne	bad43
	cmp.l	#$1234567a,(OUTC+4).l
	beq	ok43
bad43:
	move.w	#43,d7
	jmp	failed
ok43:
	fmove.s	#0.0,fp1
	moveq	#1,d1
	fadd.d	0(a0,d1.l*8),fp1
	fmove.d	fp1,(OUTC).l
	cmp.l	#$40001000,(OUTC).l
	bne	bad44
	cmp.l	#$12345679,(OUTC+4).l
	beq	ok44
bad44:
	move.w	#44,d7
	jmp	failed
ok44:
; ---- single stores
	move.l	#$a5a5a5a5,($6100).l
	move.l	#$a5a5a5a5,($6104).l
	move.l	#$a5a5a5a5,($6108).l
	move.l	#$a5a5a5a5,($610c).l
	move.l	#$a5a5a5a5,($6110).l
	move.l	#$a5a5a5a5,($6114).l
	move.l	#$a5a5a5a5,($6118).l
	move.l	#$a5a5a5a5,($611c).l
	move.l	#$a5a5a5a5,($6120).l
	move.l	#$a5a5a5a5,($6124).l
	move.l	#$a5a5a5a5,($6128).l
	move.l	#$a5a5a5a5,($612c).l
	move.l	#$a5a5a5a5,($6130).l
	move.l	#$a5a5a5a5,($6134).l
	move.l	#$a5a5a5a5,($6138).l
	move.l	#$a5a5a5a5,($613c).l
	lea	$6100,a4
	fmove.s	($5004).l,fp0
	fmove.s	fp0,8(a4)
	cmp.l	#$40001000,($6108).l
	beq	ok45
	move.w	#45,d7
	jmp	failed
ok45:
	cmp.l	#$a5a5a5a5,($6104).l
	beq	ok46
	move.w	#46,d7
	jmp	failed
ok46:
	cmp.l	#$a5a5a5a5,($610c).l
	beq	ok47
	move.w	#47,d7
	jmp	failed
ok47:
	moveq	#4,d1
	fmove.s	($5008).l,fp0
	fmove.s	fp0,4(a4,d1.l*4)
	cmp.l	#$40002000,($6114).l
	beq	ok48
	move.w	#48,d7
	jmp	failed
ok48:
	cmp.l	#$a5a5a5a5,($6110).l
	beq	ok49
	move.w	#49,d7
	jmp	failed
ok49:
	cmp.l	#$a5a5a5a5,($6118).l
	beq	ok50
	move.w	#50,d7
	jmp	failed
ok50:
	move.l	#$fffe0007,d1
	fmove.s	($500c).l,fp0
	fmove.s	fp0,-4(a4,d1.w*4)
	cmp.l	#$40003000,($6118).l
	beq	ok51
	move.w	#51,d7
	jmp	failed
ok51:
	fmove.s	($5010).l,fp0
	moveq	#$20,d3
	fmove.s	fp0,0(a4,d3.l)
	cmp.l	#$40004000,($6120).l
	beq	ok52
	move.w	#52,d7
	jmp	failed
ok52:
	fmove.s	($5014).l,fp0
	lea	$6100,a3
	fmove.s	fp0,$24(a3)
	cmp.l	#$40005000,($6124).l
	beq	ok53
	move.w	#53,d7
	jmp	failed
ok53:
	fmove.s	($5018).l,fp0
	move.l	#$28,a1
	fmove.s	fp0,0(a4,a1.l)
	cmp.l	#$40006000,($6128).l
	beq	ok54
	move.w	#54,d7
	jmp	failed
ok54:
	fmove.s	($501c).l,fp0
	fmove.s	fp0,(-4.l,a4,a1.l)
	cmp.l	#$40007000,($6124).l
	beq	ok55
	move.w	#55,d7
	jmp	failed
ok55:
; ---- arith result stored to displacement / indexed (P255 + P256)
	fmove.s	#1.5,fp0
	fadd.s	#1.5,fp0
	fmove.s	fp0,$2c(a4)
	cmp.l	#$40400000,($612c).l
	beq	ok56
	move.w	#56,d7
	jmp	failed
ok56:
	fmove.s	#3.0,fp2
	fmul.s	#0.5,fp2
	moveq	#$30,d1
	fmove.s	fp2,0(a4,d1.l)
	cmp.l	#$3fc00000,($6130).l
	beq	ok57
	move.w	#57,d7
	jmp	failed
ok57:
; ---- double stores
	fmove.d	($5408).l,fp1
	fmove.d	fp1,$38(a4)
	cmp.l	#$40001000,($6138).l
	beq	ok58
	move.w	#58,d7
	jmp	failed
ok58:
	cmp.l	#$12345679,($613c).l
	beq	ok59
	move.w	#59,d7
	jmp	failed
ok59:
	cmp.l	#$a5a5a5a5,($6134).l
	beq	ok60
	move.w	#60,d7
	jmp	failed
ok60:
	fmove.d	($5410).l,fp1
	moveq	#8,d1
	fmove.d	fp1,$38(a4,d1.l*2)
	cmp.l	#$40002000,($6148).l
	beq	ok61
	move.w	#61,d7
	jmp	failed
ok61:
	cmp.l	#$1234567a,($614c).l
	beq	ok62
	move.w	#62,d7
	jmp	failed
ok62:
	fmove.s	#2.5,fp1
	fsub.s	#0.5,fp1
	fmove.d	fp1,-8(a4,d1.l*8)
	cmp.l	#$40000000,($6138).l
	beq	ok63
	move.w	#63,d7
	jmp	failed
ok63:
	cmp.l	#$00000000,($613c).l
	beq	ok64
	move.w	#64,d7
	jmp	failed
ok64:
; ---- extended loads/stores with d16 (non-shortcut format)
	fmove.s	($5020).l,fp0
	fmove.x	fp0,$50(a4)
	fmove.x	$50(a4),fp2
	moveq	#$60,d1
	fmove.s	fp2,0(a4,d1.l)
	cmp.l	#$40008000,($6160).l
	beq	ok65
	move.w	#65,d7
	jmp	failed
ok65:
	fmove.l	#12345,fp0
	fmove.l	fp0,$64(a4)
	cmp.l	#$00003039,($6164).l
	beq	ok66
	move.w	#66,d7
	jmp	failed
ok66:
	moveq	#$68,d1
	fmove.w	#-7,fp0
	fmove.l	fp0,0(a4,d1.l)
	cmp.l	#$fffffff9,($6168).l
	beq	ok67
	move.w	#67,d7
	jmp	failed
ok67:
    move.w #$600d,($f102).l
    stop #$2700
    cnop 0,4
pcd:
    dc.l $40091eb8,$51eb851f
ptr:
    dc.l 0
failed:
    move.w d7,($f100).l
    move.w #$bad0,($f102).l
    stop #$2700
    org $5000
    dc.l $40000000
    dc.l $40001000
    dc.l $40002000
    dc.l $40003000
    dc.l $40004000
    dc.l $40005000
    dc.l $40006000
    dc.l $40007000
    dc.l $40008000
    dc.l $40009000
    dc.l $4000a000
    dc.l $4000b000
    dc.l $4000c000
    dc.l $4000d000
    dc.l $4000e000
    dc.l $4000f000
    dc.l $40010000
    dc.l $40011000
    dc.l $40012000
    dc.l $40013000
    dc.l $40014000
    dc.l $40015000
    dc.l $40016000
    dc.l $40017000
    dc.l $40018000
    dc.l $40019000
    dc.l $4001a000
    dc.l $4001b000
    dc.l $4001c000
    dc.l $4001d000
    dc.l $4001e000
    dc.l $4001f000
    dc.l $40020000
    dc.l $40021000
    dc.l $40022000
    dc.l $40023000
    dc.l $40024000
    dc.l $40025000
    dc.l $40026000
    dc.l $40027000
    dc.l $40028000
    dc.l $40029000
    dc.l $4002a000
    dc.l $4002b000
    dc.l $4002c000
    dc.l $4002d000
    dc.l $4002e000
    dc.l $4002f000
    dc.l $40030000
    dc.l $40031000
    dc.l $40032000
    dc.l $40033000
    dc.l $40034000
    dc.l $40035000
    dc.l $40036000
    dc.l $40037000
    dc.l $40038000
    dc.l $40039000
    dc.l $4003a000
    dc.l $4003b000
    dc.l $4003c000
    dc.l $4003d000
    dc.l $4003e000
    dc.l $4003f000
    org $5400
    dc.l $40000000,$12345678
    dc.l $40001000,$12345679
    dc.l $40002000,$1234567a
    dc.l $40003000,$1234567b
    dc.l $40004000,$1234567c
    dc.l $40005000,$1234567d
    dc.l $40006000,$1234567e
    dc.l $40007000,$1234567f
    dc.l $40008000,$12345680
    dc.l $40009000,$12345681
    dc.l $4000a000,$12345682
    dc.l $4000b000,$12345683
    dc.l $4000c000,$12345684
    dc.l $4000d000,$12345685
    dc.l $4000e000,$12345686
    dc.l $4000f000,$12345687
