#!/usr/bin/env python3
"""Whetstone fixture on the shipped memory path: quadra800 + sdram_beat32 +
sdram.sv + the tb_sdram chip model, all RTL from TREE=<dir containing rtl/>.

  TREE=scratch/tree_p205 scripts/cpu/platform_fixture/run_platform_whet.py --out DIR
      [--image RAM.bin] [--rom ROM] [--romlat N] [--ref DIR_WITH_REFERENCE_HEX]

Prints WHETSTONE_LOOP / WHETSTONE RETURNED and the instrumentation summary;
the full log is DIR/run.log.  EXTRA_FLAGS / EXTRA_PLUSARGS pass through.
"""
import argparse, hashlib, json, os, re, subprocess, sys
from pathlib import Path

R = next(x for x in Path(__file__).resolve().parents
         if (x/'MacQuadra800.qsf').is_file() and (x/'verilator/tb_sdram.sv').is_file())
HERE = Path(__file__).resolve().parent
VERILATOR = '/home/alans/verilator5/bin/verilator'

p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
p.add_argument('--image', type=Path, default=R/'scratch/whetstone_full_fixture_20260920/ram.bin')
p.add_argument('--rom', type=Path, default=R/'releases/quadra800.rom')
p.add_argument('--out', type=Path, required=True)
p.add_argument('--romlat', type=int, default=6, help='clk_sys cycles from a ROM beat request to its ack (DDR3 stand-in)')
p.add_argument('--ref', type=Path, default=R/'scratch/p198_ret/wl_p205_1',
               help='directory with whet_{globals,code,stack}.hex from the latency fixture, compared byte for byte')
p.add_argument('--no-compile', action='store_true')
a = p.parse_args()

tree = Path(os.environ['TREE']).resolve()
rtl = tree/'rtl'
ap = rtl/'ap68040/rtl'
d = a.out.resolve(); d.mkdir(parents=True, exist_ok=True)

# The chip model is tb_sdram.sv's, unchanged except for its storage: the
# associative array becomes a flat 32M-word array (an unwritten cell reads 0,
# not $FFFF) so the 32 MB image can be backdoor-loaded without a 16M-entry map.
src = (R/'verilator/tb_sdram.sv').read_text()
model = src[src.index('module sdram_model'):]
subs = [('bit [15:0] mem [int];', 'bit [15:0] mem [0:33554431];'),
        ('mem.exists(k) ? mem[k] : 16\'hFFFF', 'mem[k]'),
        ('if (!mem.exists(k)) mem[k] = 16\'hFFFF;', '')]
for old, new in subs:
    assert old in model, old
    model = model.replace(old, new)
assert 'exists' not in model
flat = d/'sdram_model_flat.sv'
flat.write_text('// GENERATED by run_platform_whet.py from verilator/tb_sdram.sv (storage flattened)\n`timescale 1ps/1ps\n' + model)

units = ['ap040_core', 'ap040_bus_timeout', 'ap040_regfile', 'ap040_alu', 'ap040_muldiv',
         'ap040_mmu', 'ap040_cache', 'ap040_fpu']
sources = [HERE/'tb_platform_whet.sv', flat, R/'verilator/altddio_out_stub.v']
sources += [rtl/f for f in ['quadra800.sv', 'wombat_cpu.sv', 'wombat_store_buffer.sv', 'wombat_bus32.sv',
            'sdram_beat32.sv', 'sdram.sv', 'iosb.sv', 'via6522.sv', 'dafb.sv', 'rtc3430042.sv', 'easc.sv',
            'ncr53c96.sv', 'sonic_mbx.sv', 'cd_audio.sv', 'scsi_cache.sv', 'adb.sv', 'scc.v',
            'uart/txuart.v', 'uart/rxuart.v', 'dpram.v']]
sources += [rtl/'ap68040/experimental/ap040_pipeline_integer.sv'] + [ap/(u+'.v') for u in units]
# the release recipe's CPU and area switches (MacQuadra800.qsf VERILOG_MACRO)
flags = ['-DAP040_EXPERIMENTAL_'+x for x in ('XSTORE', 'LEA', 'PIPELINE', 'PIPELINE_LOADS', 'PIPELINE_STORES',
                                            'PIPELINE_PEA', 'PIPELINE_P6')]
flags += ['-DAP040_PIPELINE_MEMORY_ENTRY', '-DAP040_PIPELINE_COMPARE', '-DAP040_PIPELINE_EARLY_DRAIN',
          '-DCACHE_CD_OFF=1', '-DCACHE_SMALL=1', '-DSIMULATION=1']  # SIMULATION: behavioural BRAMs, as the full-machine sim
flags += os.environ.get('EXTRA_FLAGS', '').split()
active_macros = set(re.findall(r'^set_global_assignment -name VERILOG_MACRO "([A-Z0-9_]+)=1"',
                               (R/'MacQuadra800.qsf').read_text(), re.M))
for flag in flags:
    if flag.startswith('-DAP040_') or flag in ('-DCACHE_CD_OFF=1', '-DCACHE_SMALL=1'):
        assert flag[2:].split('=')[0] in active_macros, f'fixture flag absent from qsf: {flag}'
assert {x for x in active_macros if x.startswith('AP040_')} == {
    f[2:].split('=')[0] for f in flags if f.startswith('-DAP040_')
}, 'fixture AP040 flags no longer match release qsf'

(d/'identity.json').write_text(json.dumps({
    'tree': str(tree),
    'sources': {str(f): hashlib.sha256(Path(f).read_bytes()).hexdigest() for f in sources},
    'image_sha256': hashlib.sha256(a.image.read_bytes()).hexdigest(),
    'rom_sha256': hashlib.sha256(a.rom.read_bytes()).hexdigest(),
    'flags': flags, 'romlat': a.romlat}, indent=2) + '\n')

def run(cmd, log):
    with (d/log).open('w') as f:
        r = subprocess.run(list(map(str, cmd)), cwd=d, stdout=f, stderr=subprocess.STDOUT)
    text = (d/log).read_text(errors='replace')
    if r.returncode:
        sys.exit(f'{log} failed:\n' + text[-4000:])
    return text

if not a.no_compile:
    warn = ['-Wno-fatal', '-Wno-WIDTH', '-Wno-WIDTHEXPAND', '-Wno-WIDTHTRUNC', '-Wno-IMPLICIT', '-Wno-PINMISSING',
            '-Wno-UNUSEDSIGNAL', '-Wno-UNOPTFLAT', '-Wno-CASEINCOMPLETE', '-Wno-UNSIGNED', '-Wno-CMPCONST',
            '-Wno-LATCH', '-Wno-UNDRIVEN', '-Wno-MISINDENT', '-Wno-COMBDLY', '-Wno-INITIALDLY',
            '-Wno-SYNCASYNCNET', '-Wno-BLKLOOPINIT', '-Wno-MULTIDRIVEN', '-Wno-GENUNNAMED', '-Wno-DECLFILENAME',
            '-Wno-TIMESCALEMOD', '-Wno-BLKSEQ']
    run([VERILATOR, '--binary', '--timing', '-O3', '--unroll-count', '256',
         '--x-assign', 'fast', '--x-initial', 'fast', '--noassert',
         '-j', '8', '--build-jobs', '8', '--timescale-override', '1ps/1ps', *warn,
         '--top-module', 'tb_platform_whet', '--Mdir', d/'obj', '-I'+str(rtl), '-I'+str(ap), *flags, *sources],
        'compile.log')

text = run(['stdbuf', '-oL', d/'obj/Vtb_platform_whet', '+prog='+str(a.image.resolve()), '+rom='+str(a.rom.resolve()),
            f'+romlat={a.romlat}', *os.environ.get('EXTRA_PLUSARGS', '').split()], 'run.log')
assert 'WHETSTONE RETURNED' in text, text[-3000:]
keep = ('WHETSTONE', 'BUS32', 'SDRAM', 'BERR', 'CORE_LAT', 'EXT', 'WALKER', 'STOREBUF', 'BRIDGE')
print('\n'.join(l for l in text.splitlines() if l.startswith(keep)))

if a.ref and (a.ref/'whet_globals.hex').exists():
    for n in ('whet_globals.hex', 'whet_code.hex', 'whet_stack.hex'):
        mine = [x.strip().lower() for x in (d/n).read_text().split()]
        ref = [x.strip().lower() for x in (a.ref/n).read_text().split() if not x.startswith('//')]
        print(f'MEMCHECK {n}: ' + ('match' if mine == ref else
              f'DIFFER ({sum(1 for x, y in zip(mine, ref) if x != y)} bytes of {len(ref)})'))
