#!/usr/bin/env python3
"""Whetstone fixture on the shipped memory path: quadra800 + sdram_beat32 +
sdram.sv + the tb_sdram chip model, all RTL from TREE=<dir containing rtl/>.

  TREE=scratch/tree_p205 scripts/cpu/platform_fixture/run_platform_whet.py --out DIR
      [--image RAM.bin] [--rom ROM] [--romlat N] [--ref DIR_WITH_REFERENCE_HEX]

Prints WHETSTONE_LOOP / WHETSTONE RETURNED and the instrumentation summary;
the full log is DIR/run.log.  EXTRA_FLAGS / EXTRA_PLUSARGS pass through.
"""
import argparse, hashlib, json, os, re, subprocess, sys, runpy, contextlib, io
from pathlib import Path

R = next(x for x in Path(__file__).resolve().parents
         if (x/'MacQuadra800.qsf').is_file() and (x/'verilator/tb_sdram.sv').is_file())
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE/'reference'))
from check_payloads import verify_matrix_payloads
VERILATOR = '/home/alans/verilator5/bin/verilator'

p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
p.add_argument('--image', type=Path, default=HERE/'ram.bin')
p.add_argument('--rom', type=Path, default=R/'releases/quadra800.rom')
p.add_argument('--out', type=Path, required=True)
p.add_argument('--romlat', type=int, default=6, help='clk_sys cycles from a ROM beat request to its ack (DDR3 stand-in)')
p.add_argument('--no-compile', action='store_true')
a = p.parse_args()

native_identity=json.loads((HERE/'image_identity.json').read_text())
assert native_identity['selector']==3 and native_identity['resource_sha256']=='34ee511807b66d2360c505b352d0946c01730d764843ed815cfd49bab2fa8aa0'
assert hashlib.sha256(a.image.read_bytes()).hexdigest()==native_identity['output_sha256'],'native image identity'
tree = Path(os.environ['TREE']).resolve()
rtl = tree/'rtl'
ap = rtl/'ap68040/rtl'
d = a.out.resolve(); assert not d.exists(), "fresh output directory required"; d.mkdir(parents=True)

# The chip model is tb_sdram.sv's, unchanged except for its storage: the
# associative array becomes a flat 32M-word array (an unwritten cell reads 0,
# not $FFFF) so the 32 MB image can be backdoor-loaded without a 16M-entry map.
src = (R/'verilator/tb_sdram.sv').read_text()
model = src[src.index('module sdram_model'):]
subs = [('bit [15:0] mem [int];', 'bit [15:0] mem [0:33554431];'),
        ('mem.exists(k) ? mem[k] : 16\'hFFFF', 'mem[k]'),
        ('if (!mem.exists(k)) mem[k] = 16\'hFFFF;', '')]
for old, new in subs:
    assert old in model, old
    model = model.replace(old, new)
assert 'exists' not in model
flat = d/'sdram_model_flat.sv'
flat.write_text('// GENERATED by run_platform_whet.py from verilator/tb_sdram.sv (storage flattened)\n`timescale 1ps/1ps\n' + model)

units = ['ap040_core', 'ap040_bus_timeout', 'ap040_regfile', 'ap040_alu', 'ap040_muldiv',
         'ap040_mmu', 'ap040_cache', 'ap040_fpu']
sources = [HERE/'tb_platform_whet.sv', flat, R/'verilator/altddio_out_stub.v']
sources += [rtl/f for f in ['quadra800.sv', 'wombat_cpu.sv', 'wombat_store_buffer.sv', 'wombat_bus32.sv',
            'sdram_beat32.sv', 'sdram.sv', 'iosb.sv', 'via6522.sv', 'dafb.sv', 'rtc3430042.sv', 'easc.sv',
            'ncr53c96.sv', 'sonic_mbx.sv', 'cd_audio.sv', 'scsi_cache.sv', 'adb.sv', 'scc.v',
            'uart/txuart.v', 'uart/rxuart.v', 'dpram.v']]
sources += [rtl/'ap68040/experimental/ap040_pipeline_integer.sv'] + [ap/(u+'.v') for u in units]
# the release recipe's CPU and area switches (MacQuadra800.qsf VERILOG_MACRO)
flags = ['-DAP040_EXPERIMENTAL_'+x for x in ('XSTORE', 'LEA', 'PIPELINE', 'PIPELINE_LOADS', 'PIPELINE_STORES',
                                            'PIPELINE_PEA', 'PIPELINE_P6')]
flags += ['-DAP040_PIPELINE_MEMORY_ENTRY', '-DAP040_PIPELINE_COMPARE', '-DAP040_PIPELINE_EARLY_DRAIN',
          '-DCACHE_CD_OFF=1', '-DCACHE_SMALL=1', '-DSIMULATION=1']  # SIMULATION: behavioural BRAMs, as the full-machine sim
flags += os.environ.get('EXTRA_FLAGS', '').split()
active_macros = set(re.findall(r'^set_global_assignment -name VERILOG_MACRO "([A-Z0-9_]+)=1"',
                               (R/'MacQuadra800.qsf').read_text(), re.M))
for flag in flags:
    if flag.startswith('-DAP040_') or flag in ('-DCACHE_CD_OFF=1', '-DCACHE_SMALL=1'):
        assert flag[2:].split('=')[0] in active_macros, f'fixture flag absent from qsf: {flag}'
assert {x for x in active_macros if x.startswith('AP040_')} == {
    f[2:].split('=')[0] for f in flags if f.startswith('-DAP040_')
}, 'fixture AP040 flags no longer match release qsf'

(d/'identity.json').write_text(json.dumps({
    'tree': str(tree),
    'sources': {str(f): hashlib.sha256(Path(f).read_bytes()).hexdigest() for f in sources},
    'image_sha256': hashlib.sha256(a.image.read_bytes()).hexdigest(),
    'rom_sha256': hashlib.sha256(a.rom.read_bytes()).hexdigest(),
    'flags': flags, 'romlat': a.romlat,
    'numeric_oracle_sha256': hashlib.sha256((HERE/'reference/fppm_oracle.py').read_bytes()).hexdigest(),
    'payload_checker_sha256': hashlib.sha256((HERE/'reference/check_payloads.py').read_bytes()).hexdigest()}, indent=2) + '\n')

def run(cmd, log):
    with (d/log).open('w') as f:
        r = subprocess.run(list(map(str, cmd)), cwd=d, stdout=f, stderr=subprocess.STDOUT, timeout=600)
    text = (d/log).read_text(errors='replace')
    if r.returncode:
        sys.exit(f'{log} failed:\n' + text[-4000:])
    return text

if not a.no_compile:
    warn = ['-Wno-fatal', '-Wno-WIDTH', '-Wno-WIDTHEXPAND', '-Wno-WIDTHTRUNC', '-Wno-IMPLICIT', '-Wno-PINMISSING',
            '-Wno-UNUSEDSIGNAL', '-Wno-UNOPTFLAT', '-Wno-CASEINCOMPLETE', '-Wno-UNSIGNED', '-Wno-CMPCONST',
            '-Wno-LATCH', '-Wno-UNDRIVEN', '-Wno-MISINDENT', '-Wno-COMBDLY', '-Wno-INITIALDLY',
            '-Wno-SYNCASYNCNET', '-Wno-BLKLOOPINIT', '-Wno-MULTIDRIVEN', '-Wno-GENUNNAMED', '-Wno-DECLFILENAME',
            '-Wno-TIMESCALEMOD', '-Wno-BLKSEQ']
    run([VERILATOR, '--binary', '--timing', '-O3', '--unroll-count', '256',
         '--x-assign', 'fast', '--x-initial', 'fast', '--noassert',
         '-j', '2', '--build-jobs', '2', '--timescale-override', '1ps/1ps', *warn,
         '--top-module', 'tb_platform_whet', '--Mdir', d/'obj', '-I'+str(rtl), '-I'+str(ap), *flags, *sources],
        'compile.log')

text = run(['stdbuf', '-oL', d/'obj/Vtb_platform_whet', '+prog='+str(a.image.resolve()), '+rom='+str(a.rom.resolve()),
            f'+romlat={a.romlat}', *os.environ.get('EXTRA_PLUSARGS', '').split()], 'run.log')
assert 'WHETSTONE RETURNED' in text, text[-3000:]
loop_match=re.search(r'WHETSTONE_LOOP cycles=(\d+)', text)
assert loop_match and int(loop_match[1])==29_640_994, 'numeric candidate run loop clocks differ from separately qualified FPU candidate run2'
keep = ('WHETSTONE', 'BUS32', 'SDRAM', 'BERR', 'CORE_LAT', 'EXT', 'WALKER', 'STOREBUF', 'BRIDGE', 'FPU_ELIG', 'NATIVE')
print('\n'.join(l for l in text.splitlines() if l.startswith(keep)))

abi=bytes(int(x,16) for x in (d/'native_abi.hex').read_text().split())
expected=[0x11110003,0x11110004,0x11110005,0x11110006,0x11110007,0x22222222,0x33333333,0x600000,0x620000,0x66666666]
assert abi[:40]==b''.join(x.to_bytes(4,'big') for x in expected),'initial sentinels'
assert abi[:40]==abi[0x40:0x68],'D3-D7/A2-A6 preservation'
assert int.from_bytes(abi[0x80:0x84],'big')==0x608ea0,'returned resource localA4'
assert int.from_bytes(abi[0x84:0x88],'big')==0x640000 and abi[0x84:0x88]==abi[0x88:0x8c],'stack cleanup'
assert abi[0x100:0x130]==abi[0x140:0x170],'FP4-FP7 preservation'
fpchunks=[abi[0x100+i*12:0x10c+i*12] for i in range(4)]
assert set(fpchunks)=={bytes.fromhex('40020000'+m+'00000000000000') for m in ['b0','c0','d0','e0']},'seeded FP sentinels'
code=bytes(int(x,16) for x in (d/'native_code.hex').read_text().split())
assert code==(a.image.read_bytes())[0x600000:0x600ea0],'native code unmodified'
print('NATIVE_ABI D3_D7_A2_A6=match FP4_FP7=match SP=640000 A4=600000 D0=608EA0 code=unchanged')
assert 'SDRAM_PROTOCOL_ERRORS 0' in text, 'chip errors'
assert re.search(r'BERR 0\s+IPL_ASSERTED_CYCLES 0',text), 'bus error or IRQ'
assert 'MATRIX_TRAPS alloc_calls=123 alloc_returns=123 free_calls=123 free_returns=123' in text, 'Matrix trap lifecycle'
print('NATIVE_QUALIFIED native_allocator_coverage=1 ABI_match=1 guest_600D=1 chip_errors=0')

# Compare all live 1-based Matrix payload cells against the frozen independent
# oracle. The allocated row 0/column 0 are intentionally outside this check.
with contextlib.redirect_stdout(io.StringIO()):
    oracle=runpy.run_path(str(HERE/'reference/fppm_oracle.py'))
assert 'MATRIX_NUMERIC_CAPTURE_GUARDS_PASS' in text
assert 'MATRIX_NUMERIC_CAPTURE files=123 bytes_each=164 first_free_pc=000600260' in text
verify_matrix_payloads(d, oracle)
print('MATRIX_NUMERIC_ORACLE PASS cells=4800 format=binary32_be rows=1..40 cols=1..40 row0_col0=skipped')
